language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "CVsL7JRSMTXIeWtVtRBNDXdoJr6UWqqqiTZKnDUXATOzajU9U47vEX94y4VrcRVz4Rl0MPrCufYUEL3qD33itnkFe86iViOjIocKJkme8A5XDcSLOnLcSx1tvp8jeRey1rPnoK15M1yDji4Q4zafHWskDUDooFGgqFY3NNSf8fCdUmgVHBPDa1j8Y+0SZmr4/VneWwOcIp4Nj69xhozIodyuLJ9+d8fpMMRT05xM5TukmntO4E5HebM+OKP0B9Gs34dZ1l9LCtqSjhSJEFLeHfwXinnQl38ujLyCn9WEJk1Nvye2md5tfXx66B+C8kvegXqbJl4EXi+s67cJCLcIfz7tK1b3genGYflxGf1/+sL4ahkS3ay+izlpqFHVgQZcDMeAWJWjHj5G+Z7YZ/WtRc+sJOORyv4d1cJEds5wWvRh9aL683e3yzuotqHsng+PtkB0rLChC3OLIKibm2nHyxNbmBlC/hp8dMNeguw3TnF87sb5qcAYOP7Jk1y962OMq4goeiM/tkuum4K9eC8TIOHWmEyP78mHFSa0wy04JUY5cA67qZvfcpn49JpzVbSmzd/J+XIgOYtE5iaFEIaIbU8MLCZyROTszOaH12RLFS9I/egFLKAhXK3kDgsypq3eR+QfLz9GsQaeUFPaNc5FKz4EUm95R0+D2oiyKsuykgU="